#!/usr/bin/env python3
"""Dry-run-first importer for one reviewed staging Catalog candidate.

The source candidate file is generated by ``data:preflight`` and is ignored by
Git. Requests are delegated to the official ``cloudflared access curl``
wrapper, which uses the operator's authenticated Access session without this
script printing or persisting an Access token.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import unicodedata
from pathlib import Path
from typing import Any


DEFAULT_CANDIDATES = Path(
    "test-exports/staging/source-preflight/catalog_candidates.json"
)
DEFAULT_BASE_URL = (
    "https://hirebeat-operations-api-v1.shiyilidorothy.workers.dev"
)
DEFAULT_COMPANY = "ags logistics"
DEFAULT_POSITION = "operations data analyst (on-site)"


def normalize(value: Any) -> str:
    return re.sub(
        r"\s+",
        " ",
        unicodedata.normalize("NFKC", "" if value is None else str(value)).strip(),
    ).lower()


def stable_key(kind: str, *parts: str) -> str:
    digest = hashlib.sha256("\x1f".join(parts).encode("utf-8")).hexdigest()[:24]
    return f"staging-seed-{kind}-{digest}"


def load_candidate(path: Path, company: str, position: str) -> dict[str, Any]:
    if not path.is_file():
        raise ValueError(
            f"candidate_file_missing:{path}; run npm run data:preflight first"
        )
    document = json.loads(path.read_text(encoding="utf-8"))
    matches = [
        row
        for row in document.get("deterministic_candidates", [])
        if row.get("normalized_company_name") == company
        and row.get("normalized_position_name") == position
    ]
    if len(matches) != 1:
        raise ValueError(f"candidate_match_count:{len(matches)}")
    candidate = matches[0]
    jd = str(candidate.get("position_jd") or "").strip()
    if len(jd) < 10:
        raise ValueError("candidate_position_jd_missing_or_too_short")
    return candidate


def request_json(
    base_url: str,
    method: str,
    path: str,
    payload: dict[str, Any] | None = None,
) -> dict[str, Any]:
    url = f"{base_url.rstrip('/')}{path}"
    command = [
        "cloudflared",
        "access",
        "curl",
        url,
        "--silent",
        "--show-error",
        "--fail-with-body",
        "--request",
        method,
        "--header",
        "accept: application/json",
    ]
    body = None
    if payload is not None:
        body = json.dumps(payload, ensure_ascii=False)
        command.extend(
            [
                "--header",
                "content-type: application/json",
                "--data-binary",
                "@-",
            ]
        )
    try:
        completed = subprocess.run(
            command,
            input=body,
            check=True,
            capture_output=True,
            text=True,
            timeout=45,
        )
    except FileNotFoundError as error:
        raise RuntimeError("cloudflared_not_installed") from error
    except subprocess.TimeoutExpired as error:
        raise RuntimeError("operations_api_request_timed_out") from error
    except subprocess.CalledProcessError as error:
        detail = (error.stdout or error.stderr or "").strip()
        raise RuntimeError(f"operations_api_request_failed:{detail[:500]}") from error
    try:
        value = json.loads(completed.stdout)
    except json.JSONDecodeError as error:
        raise RuntimeError("operations_api_non_json_response") from error
    if not isinstance(value, dict):
        raise RuntimeError("operations_api_json_object_expected")
    return value


def make_plan(candidate: dict[str, Any], work_mode_id: int) -> dict[str, Any]:
    company = str(candidate["normalized_company_name"])
    position = str(candidate["normalized_position_name"])
    jd = str(candidate["position_jd"]).strip()
    jd_hash = hashlib.sha256(jd.encode("utf-8")).hexdigest()
    return {
        "schema_version": "hirebeat-reviewed-staging-catalog-seed-v1",
        "source": {
            "candidate_kind": "deterministic_single_version",
            "company_name": candidate["company_name"],
            "normalized_company_name": company,
            "position_name": candidate["position_name"],
            "normalized_position_name": position,
            "position_jd_character_count": len(jd),
            "position_jd_sha256": jd_hash,
            "source_row_count": candidate["source_row_count"],
        },
        "commands": {
            "company": {
                "idempotency_key": stable_key("company", company),
                "company_name": candidate["company_name"],
            },
            "company_work_mode": {
                "idempotency_key": stable_key(
                    "company-work-mode", company, str(work_mode_id)
                ),
                "work_mode_id": work_mode_id,
            },
            "position": {
                "idempotency_key": stable_key(
                    "position", company, position, jd_hash
                ),
                "position_name": candidate["position_name"],
                "position_jd": jd,
            },
            "catalog_revision": {
                "idempotency_key": stable_key(
                    "catalog-revision", company, position, jd_hash, str(work_mode_id)
                ),
                "change_reason": (
                    "Reviewed staging seed from deterministic private-source preflight"
                ),
            },
        },
    }


def redacted_plan(value: dict[str, Any]) -> dict[str, Any]:
    copy = json.loads(json.dumps(value))
    position = copy["commands"]["position"]
    position["position_jd"] = {
        "redacted": True,
        "character_count": copy["source"]["position_jd_character_count"],
        "sha256": copy["source"]["position_jd_sha256"],
    }
    return copy


def apply_plan(base_url: str, value: dict[str, Any]) -> dict[str, Any]:
    commands = value["commands"]
    company = request_json(
        base_url, "POST", "/v1/catalog/companies", commands["company"]
    )
    company_id = int(company["company_id"])
    company_work_mode = request_json(
        base_url,
        "POST",
        "/v1/catalog/company-work-modes",
        {**commands["company_work_mode"], "company_id": company_id},
    )
    position = request_json(
        base_url,
        "POST",
        "/v1/catalog/positions",
        {**commands["position"], "company_id": company_id},
    )
    revision = request_json(
        base_url,
        "POST",
        "/v1/catalog/revisions",
        commands["catalog_revision"],
    )
    options = request_json(base_url, "GET", "/v1/catalog/options")
    return {
        "company": company,
        "company_work_mode": company_work_mode,
        "position": position,
        "catalog_revision": revision,
        "catalog_counts": {
            "companies": len(options.get("companies", [])),
            "company_work_modes": len(options.get("company_work_modes", [])),
            "positions": len(options.get("positions", [])),
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--candidates", type=Path, default=DEFAULT_CANDIDATES)
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--company", default=DEFAULT_COMPANY)
    parser.add_argument("--position", default=DEFAULT_POSITION)
    parser.add_argument("--work-mode-id", type=int, default=1)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument(
        "--confirm",
        help="Required with --apply; must equal '<normalized company>|<normalized position>'.",
    )
    args = parser.parse_args()

    company = normalize(args.company)
    position = normalize(args.position)
    if args.work_mode_id <= 0:
        raise ValueError("work_mode_id_must_be_positive")
    candidate = load_candidate(args.candidates, company, position)
    value = make_plan(candidate, args.work_mode_id)
    print(json.dumps(redacted_plan(value), indent=2, ensure_ascii=False))

    if not args.apply:
        print("DRY RUN ONLY: no network request or database write was performed.")
        print(f"Confirmation value: {company}|{position}")
        return 0

    expected = f"{company}|{position}"
    if args.confirm != expected:
        raise ValueError(f"confirmation_mismatch:expected:{expected}")
    result = apply_plan(args.base_url, value)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, RuntimeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1)
