name = "hirebeat-operations-api-v1"
main = "src/index.ts"
compatibility_date = "2026-08-18"
workers_dev = true
preview_urls = false

[[d1_databases]]
binding = "DB"
database_name = "hirebeat_recruiting_d1_v2"
database_id = "6c4275ca-faf3-4cba-867c-8ce807c30fc6"
migrations_dir = "../../migrations"
migrations_table = "d1_migrations"

[vars]
DEPLOYMENT_STAGE = "staging"
ACCESS_TEAM_DOMAIN = "https://hirebeat-recruiting-stg-027.cloudflareaccess.com"
ACCESS_AUD = "5f60dbf34db2d7ccdb1fb9b7271bb71efe27f1f0184297ec71fd9d7d5a9deb8d"
